name: Deploy to Byet.Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Make sure we fetch all history

    - name: Deploy files to Byet.Host
      uses: SamKirkland/FTP-Deploy-Action@v3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Local directory to upload from
        git-ftp-args: --auto-init --force --remote-root /htdocs/





